grafana:
  additionalDataSources:
  - url: http://loki-gateway.logging.svc.cluster.local
    type: loki
    name: Loki
    uid: loki
    access: proxy
  extraVolumes:
  - name: custom-ca
    hostPath:
      type: Directory
      path: /etc/pki/ca-trusts/extracted/pem
  service:
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/success-codes: "200"
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
  extraVolumeMounts:
  - name: custom-ca
    mountPath: /custom-ca
    readOnly: true
  adminUser: admin
  persistence:
    storageClassName: gp3
    size: 10Gi
    accessModes:
    - ReadWriteOnce
    enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  env:
    AWS_CA_BUNDLE: /custom-ca/tls-ca-bundle.pem
crds:
  enabled: true
prometheus:
  prometheusSpec:
    volumes:
    - name: custom-ca
      hostPath:
        type: Directory
        path: /etc/pki/ca-trusts/extracted/pem
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
          accessModes:
          - ReadWriteOnce
    containers:
    - name: prometheus
      volumeMounts:
      - name: custom-ca
        mountPath: /custom-ca
        readOnly: true
      env:
      - name: AWS_CA_BUNDLE
        value: /custom-ca/tls-ca-bundle.pem
alertmanager:
  alertmanagerSpec:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
          accessModes:
          - ReadWriteOnce
  enabled: true

