alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
  enabled: true
grafana:
  env:
    AWS_CA_BUNDLE: /custom-ca/tls-ca-bundle.pem
  adminUser: admin
  extraVolumes:
  - name: custom-ca
    hostPath:
      path: /etc/pki/ca-trusts/extracted/pem
      type: Directory
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /api/health
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/success-codes: "200"
  additionalDataSources:
  - type: loki
    name: Loki
    access: proxy
    uid: loki
    url: http://loki-gateway.monitoring.svc.cluster.local
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  persistence:
    accessModes:
    - ReadWriteOnce
    storageClassName: gp3
    size: 10Gi
    enabled: true
  extraVolumeMounts:
  - name: custom-ca
    readOnly: true
    mountPath: /custom-ca
prometheus:
  prometheusSpec:
    containers:
    - env:
      - name: AWS_CA_BUNDLE
        value: /custom-ca/tls-ca-bundle.pem
      name: prometheus
      volumeMounts:
      - name: custom-ca
        readOnly: true
        mountPath: /custom-ca
    volumes:
    - name: custom-ca
      hostPath:
        path: /etc/pki/ca-trusts/extracted/pem
        type: Directory
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          storageClassName: gp3
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi
crds:
  enabled: true
