{
 "title": "Example: NATS Overview",
 "tags": [
  "example",
  "nats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Healthy NATS scrape targets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"nats-system\"} == 1)"
    }
   ]
  },
  {
   "title": "Discovered NATS scrape targets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{namespace=\"nats-system\"})"
    }
   ]
  },
  {
   "title": "NATS exporter availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "up{namespace=\"nats-system\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}