apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats-client-auth-external
  namespace: app-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: nats-client-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NATS_URL: nats://nats.nats-system.svc.cluster.local:4222
  data:
    - secretKey: NATS_USERNAME
      remoteRef:
        key: eks-nats-auth-external
        property: username
    - secretKey: NATS_PASSWORD
      remoteRef:
        key: eks-nats-auth-external
        property: password
