apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nats-auth-external
  namespace: nats-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: nats-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks-nats-auth-external
        property: username
    - secretKey: password
      remoteRef:
        key: eks-nats-auth-external
        property: password
